//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace postArticle.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class healingForestEntities : DbContext
    {
        public healingForestEntities()
            : base("name=healingForestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<Chatroom> Chatrooms { get; set; }
        public virtual DbSet<ChatroomLog> ChatroomLogs { get; set; }
        public virtual DbSet<Checkin> Checkins { get; set; }
        public virtual DbSet<CheckinReward> CheckinRewards { get; set; }
        public virtual DbSet<Collect> Collects { get; set; }
        public virtual DbSet<ExpertAnswer> ExpertAnswers { get; set; }
        public virtual DbSet<ExpertApply> ExpertApplies { get; set; }
        public virtual DbSet<Like> Likes { get; set; }
        public virtual DbSet<Message> Messages { get; set; }
        public virtual DbSet<Mood> Moods { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<R_Report> R_Report { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Report_Message> Report_Message { get; set; }
        public virtual DbSet<ReportMember> ReportMembers { get; set; }
        public virtual DbSet<RReportMember> RReportMembers { get; set; }
        public virtual DbSet<RReportMessage> RReportMessages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThanksfulThing> ThanksfulThings { get; set; }
        public virtual DbSet<UserManage> UserManages { get; set; }
        public virtual DbSet<UserQuestion> UserQuestions { get; set; }
        public virtual DbSet<articleandmessage> articleandmessages { get; set; }
        public virtual DbSet<QA> QAs { get; set; }
    }
}
