//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace postArticle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QA
    {
        public string 發問者 { get; set; }
        public string 標題 { get; set; }
        public string 內容 { get; set; }
        public System.DateTime 發問時間 { get; set; }
        public string 回答者 { get; set; }
        public string 專家回答 { get; set; }
        public System.DateTime 回覆時間 { get; set; }
    }
}
