//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace postArticle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RReportMessage
    {
        public int RMS_ID { get; set; }
        public int MS_ID { get; set; }
        public int User_ID { get; set; }
        public string Content { get; set; }
        public int Status { get; set; }
    
        public virtual Report_Message Report_Message { get; set; }
        public virtual Report_Message Report_Message1 { get; set; }
    }
}
