//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace postArticle.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserQuestion()
        {
            this.ExpertAnswer = new HashSet<ExpertAnswer>();
        }
    
        public int UserQuestionID { get; set; }
        public int UserID { get; set; }
        public string QuestionTitle { get; set; }
        public string QuestionContent { get; set; }
        public System.DateTime QuestionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpertAnswer> ExpertAnswer { get; set; }
        public virtual UserManage UserManage { get; set; }
    }
}
